FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y jq
WORKDIR /opt/chimera/bin
RUN curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/cliapp --output cliapp
RUN chmod +x cliapp
COPY ./run.sh ./run.sh
RUN chmod +x ./run.sh
# Redis integration
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
RUN mkdir /var/log/chimera

ENTRYPOINT ["./run.sh"]
