version: "3"

services:
  cliapp:
    image: pmullineux/chimera-cliapp
    volumes:
      - DATA_FOLDER:/opt/chimera/data
  webapp:
    image: pmullineux/chimera-webapp
    volumes:
      - DATA_FOLDER:/opt/chimera/data
    ports:
      - "8080:80"

volumes:
    DATA_FOLDER: 