version: "3"

services:
  cliapp:
    build: 
        context: .
        dockerfile: Dockerfile.cliapp

  webapp:
    build: 
        context: .
        dockerfile: Dockerfile.webapp

    ports:
      - "8080:80"
  redis:
    image: "redis"