FROM ubuntu:xenial
WORKDIR /opt/chimera/bin
RUN apt-get update
RUN apt-get install -y curl
RUN curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/webapp --output webapp
RUN chmod +x webapp
ENV WEBAPP_PORT=80
EXPOSE ${WEBAPP_PORT}
# Redis integration
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
RUN mkdir /var/log/chimera
ENTRYPOINT ["./webapp"]
